### ISSUE TITLE
Rename this repo to learner-home

### ISSUE THREAD

**Issue by ghassanmas** [openedx/frontend-app-learner-dashboard#140]
The configuration/toggles for this MFE are referred as mfe_home however the repo name is leaner-dashboard. 

This might create confusion. as typically (as observed) the pattern that is uesed that toggles/settings for each MFE are named as to what the MFE is called in it's repo. 

So I suggest either: 
1. rename this repo to `frontend-app-leaener-home`
2. rename its related toggle namespace to `learner_dashboard`

**Comment by deborahgu** [comment]
We don't think this needs to be done. If you still feel strongly, submit a new issue.
