### ISSUE TITLE
The dashboard doesn't respect the language cookie setting

### ISSUE THREAD

**Issue by OmarIthawi** [openedx/frontend-app-learner-dashboard#142]
### Steps to reproduce

 - Go to account setting
 - Change the language
 - Go to the learner dashboard MFE

### Expected results
 - The UI should be translated into the selected language

### Actual result
 - The UI stays in English

**Comment by ghassanmas** [comment]
@OmarIthawi I couldn't reproduce, I am using my PR though #136 not master

<img width="1416" alt="image" src="https://github.com/openedx/frontend-app-learner-dashboard/assets/16361375/d1a39c75-3a89-43cf-8336-7e05d9b82c73">

**Comment by OmarIthawi** [comment]
Thanks @ghassanmas! I'm closing this issue.
