### ISSUE TITLE
Brand logo URL is hardcoded and bypasses URL overrides for custom branding

### ISSUE THREAD

**Issue by arslanashraf7** [openedx/frontend-app-learner-dashboard#176]
#### Description:

While working on an MFE branding/customization and testing the dashboard MFE locally, I noticed that the brand logo wasn't being overridden.

I tried overriding the logo with both possible options:

1. Added a URL for [LOGO_URL](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/.env.development#L8) in the environment variable through `.env.development`
2. Replaced the logo asset/image in the brand repository that I created

#### Possible Cause

Further digging into this, I noticed that the logo URL in the dashboard MFE's BrandLogo component is [hardcoded](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/LearnerDashboardHeader/BrandLogo.jsx#L17). I assume this means it would never care for any logo URLs added through environment vars.

#### Steps to reproduce

- Setup learner dashboard MFE locally, add a value for `LOGO_URL` in the [.env.development](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/.env.development#L8)
- Load the dashboard, You should see the edX logo instead of the one from the manually added URL in step# 1.

#### Expected behavior

- The Brand logo is overridable through the URL added in the environment variables

**Comment by arbrandes** [comment]
The fix is in master.
