### ISSUE TITLE
Replace edx.org brand with openedx brand in dependencies

### ISSUE THREAD

**Issue by snglth** [openedx/frontend-app-learner-dashboard#183]
The latest master depends on [edx.org brand package](https://github.com/edx/brand-edx.org) which is not open source.

Similar issues in other MFEs:

- [ORA Grading](https://github.com/openedx/frontend-app-ora-grading/issues/199)
- [Gradebook](https://github.com/openedx/paragon/issues/2241)

**Comment by arbrandes** [comment]
Fixed!
