### ISSUE TITLE
Review on package dependencies

### ISSUE THREAD

**Issue by cintnguyen** [openedx/frontend-app-learner-dashboard#262]
When referencing requirements for an MFE [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE) , 13 is to only have hard dependencies on libraries that are either in the open edX organization or a commonly used third-party (generic NPM package) . During discovery found that:

- "@optimizely/react-sdk" requires API keys making it not readily accessible to the community, [referenced here](https://github.com/search?q=org%3Aopenedx+%40optimizely%2Freact-sdk&type=code). Is this something we can remove and replace? [On npm](https://www.npmjs.com/package/@optimizely/optimizely-sdk), it states that it is an _"A/B testing and feature management tool for product development teams that enables you to experiment at every step"_
- "react-zendesk" issues outlined in #225 , wanted to bring attention to it. Not sure if we have something internal to replace
- "@wojtekmaj/enzyme-adapter-react-17" is the unofficial adapter for react 17 from enzyme. Currently an inactive project. Can this be removed?

**Comment by justinhynes** [comment]
Thanks for bring attention to this. I have opened up an internal 2U ticket for Aperture to take a look at this and determine a path forward. It will be tracked as ticket APER-3568.

**Comment by MaxFrank13** [comment]
Optimizely removal: https://github.com/openedx/frontend-app-learner-dashboard/pull/386

**Comment by MaxFrank13** [comment]
Enzyme adapter removal: #276

**Comment by MaxFrank13** [comment]
Zendesk replacement/removal will be handled by the private ticket linked in #225
