### ISSUE TITLE
Unenrolling from Course is not working 

### ISSUE THREAD

**Issue by hinakhadim** [openedx/frontend-app-learner-dashboard#269]
When I try to unenroll from a course, the API gives error. As the API is requesting the default `.env.development` variable which is `http://localhost:18000`. But it should request to  `LMS_BASE_URL` provided in the MFE_CONFIG settings. When printing the `getConfig().LMS_BASE_URL` , it is printing the correct URL.  
<img width="1666" alt="image" src="https://github.com/openedx/frontend-app-learning/assets/112946189/2d787d42-152e-474e-8303-6b86965d9820">

**Comment by hinakhadim** [comment]
Further debugging leads me to this conclusion:
[Here](https://github.com/openedx/frontend-app-learner-dashboard/blob/bed2c341b5f7032bd56b7e5a2c7ba8e2e5404efd/src/data/services/lms/urls.js#L14), the variable is setting the first time value of `LMS_BASE_URL` because till then `mergeConfig` hasn't been run. 
For further reading, This link can be helpful. [Link](https://github.com/openedx/frontend-platform/#:~:text=When%20using%20runtime%20configuration)

I believe making `courseUneroll` a function instead of a variable will fix the issue,  so that `courseUnenroll` url picks the latest/current value of `LMS_BASE_URL`.  If this seems good, I am willing to work on it.

**Comment by justinhynes** [comment]
Thanks for your report! The Aperture team will be tracking this internally as ticket APER-3566.

**Comment by jsnwesson** [comment]
Hi @hinakhadim , the Aperture and I talked about this issue during our meeting, and we're okay with you continuing to pursue a fix for this if you have the time. I think your approach of converting the variable into a function to fetch the appropriate URL is a viable option. Let us know if you have any questions!

**Comment by hinakhadim** [comment]
Hey everyone,
Thanks for your time. I think that this issue should close automatically after merging [this PR](https://github.com/openedx/frontend-app-learner-dashboard/pull/273).

**Comment by jsnwesson** [comment]
#273 closes this issue
