### ISSUE TITLE
Not able to un-enroll

### ISSUE THREAD

**Issue by ichintanjoshi** [openedx/frontend-app-learner-dashboard#302]
**Description**: 

When a learner tries to un-enroll from a course, the URL shows it's successful, but there is no change. 
The record remain active in admin model and the enrollment is unchanged.

** Steps to reproduce ** 

- Go to Dashboard 

- Click on 3 buttons & Click on Unenroll 
![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/22208656/69063c60-954a-4b19-9899-7f0f387b61b3)

- Click on "Unenroll"
![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/22208656/71d9591e-486c-4f41-aaae-5bf3b212108f)

- Fill or don't fill the survey and submit 
![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/22208656/393d056f-8637-4342-9478-6f9ab0640c3f)

- Check on URL in request and click "Return to dashboard" 
![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/22208656/d4b9ddad-0eaf-4b07-bd1f-59eff72c301b)

**Expected Behavior** 
- Should unenroll from that course

**Actual behavior** 
- The course is still present and the user is still enrolled 

This issue is raised as result of discussion from [this forum post](https://discuss.openedx.org/t/wrong-lms-base-lms-root-url-and-others-in-tutor-17-dev/12566/4)

**Specs** 

Tutor :- 17.0.1 & 17.0.2
Open edX :- quince.1 & quince.2 
Frontend-app-learner-dashboard :- quince.1 & quince.2

**Comment by arbrandes** [comment]
@MaxFrank13 and/or @jsnwesson, is this a known issue?  (Beyond this report, of course.)  Has anybody looked into it, yet?

**Comment by jsnwesson** [comment]
@arbrandes this bug was resolved in Learner Dashboard and backported to Quince.2/3, as was mentioned [in the forum post where this discussion was captured](https://discuss.openedx.org/t/wrong-lms-base-lms-root-url-and-others-in-tutor-17-dev/12566/12). The PR is #273 . It could be the bug wasn't able to be resolved in Quince.1, but I'm not sure.
