### ISSUE TITLE
Use configured platform name in email reminder, not "edX"

### ISSUE THREAD

**Issue by kdmccormick** [openedx/frontend-app-learner-dashboard#319]
This string should use the configured platform name instead of edX:

https://github.com/openedx/frontend-app-learner-dashboard/blob/272870f7697c754cfce027ab5245c3c0d14d9bac/src/containers/LearnerDashboardHeader/ConfirmEmailBanner/messages.js#L12

![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/3628148/80747065-7d0f-43ba-9631-88d975e75be5)

```[tasklist]
### PRs
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/359
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/360
```

**Comment by e0d** [comment]
I noticed this too and this search will show all the instances that need to be updated.

https://github.com/search?q=org%3Aopenedx%20%22Remember%20to%20confirm%20your%20email%20so%20that%20you%20can%20keep%20learning%20on%20edX%22&type=code

**Comment by arbrandes** [comment]
Fixed it by the simpler expedient of not invoking the platform name at all.

**Comment by kdmccormick** [comment]
Thanks Adolfo!
