### ISSUE TITLE
Reimplement "Looking for a new challenge" panel 

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-learner-dashboard#336]
The recommendations panel implementation was removed as part of https://github.com/openedx/frontend-app-learner-dashboard/pull/311.  We should re-add the basic component as default content for the corresponding slot:

![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/3229735/b179fa2a-6db7-4e49-a9c1-ba1c582cb17f)

**Comment by MaxFrank13** [comment]
Hey @arbrandes 👋  Are there any plans to complete this work on the AXIM side? Aperture is going through the process of triaging these issues and we don't want to duplicate any efforts. Thanks!
