### ISSUE TITLE
Don't show Programs button if programs are not configured

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-learner-dashboard#372]
### Description

On a bare installation one sees the Programs button even though no programs are configured in the backend:

![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/759355/56d07bb7-d975-4cb9-a7fd-0d2731d1dae6)

The result is a 404 if you click it:

![image](https://github.com/openedx/frontend-app-learner-dashboard/assets/759355/78599484-e2e5-4e4e-b82b-50dee1d284d0)

### Expected behavior

If no programs are configured in the backend, [the button](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx#L35-L37) should simply not show.

### Implementation

While we could implement this as a config variable, ideally the frontend would detect whether programs are enabled and render the button based on that.

**Comment by justinhynes** [comment]
Thanks for the report! Aperture will track this internally as https://2u-internal.atlassian.net/browse/APER-3565. We will discuss this ticket in our next grooming session.

**Comment by arbrandes** [comment]
I've confirmed this is in the Sumac branch as well, so we're done!  Thanks @dcoa!
