### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by MaxFrank13** [openedx/frontend-app-learner-dashboard#427]
There are a handful of package dependencies that appear to be unused by the code in this repository. Some of these just need to be moved to `devDependencies` while others are not direct requirements and can at least be removed from the `package.json`. For example, the `history` package is used by `frontend-platform`, but not `frontend-app-learner-dashboard`. So when it's removed from Learner Dashboard `package.json`, it will only appear in package-lock under frontend-platform, but won't be a direct dependency for Learner Dashboard.

The below listed dependencies were chosen based on a simple search through frontend-app-learner-dashboard to see if they were utilized. Any packages that were not imported from or did not appear to be used in some other way are included in the list.

To assess for removal:

- @redux-beacon/segment
- @testing-library/user-event
- dompurify
- email-prop-type
- file-saver
- filesize
- history
- html-react-parser
- react-pdf
- redux-beacon
- universal-cookie
- whatwg-fetch

To move to `devDependencies`:

- jest
- jest-environment-jsdom
- jest-when

**Comment by jciasenza** [comment]
I can take this issue @arbrandes

**Comment by jciasenza** [comment]
i have made PR https://github.com/openedx/frontend-app-learner-dashboard/pull/447
