### ISSUE TITLE
Missing Search Bar in the Learner Dashboard?

### ISSUE THREAD

**Issue by magajh** [openedx/frontend-app-learner-dashboard#521]
#### Context  

This issue arises from the release testing of Sumac, where the following failure was reported during the test:  

> **Expected Behavior**  
> There should be a search box in the learner dashboard.  
> 
> **Actual Behavior**  
> There is no search box in the learner dashboard.  

Originally reported here: https://github.com/openedx/wg-build-test-release/issues/431

I checked the [official Open edX sandbox](https://apps.sandbox.openedx.org/), and the search box does not appear there either. I also couldn’t find anything related to a search box in this MFE (apart from the user selector for masquerading)

#### Questions  

1. Does the MFE learner dashboard include a search box/search bar? Or is the test outdated and no longer applicable?  
2. If a search box is indeed expected, could you help investigate why it is not functioning?  

Thanks!

**Comment by MaxFrank13** [comment]
Hello! Thanks for bringing this up. With regards to:

> Does the MFE learner dashboard include a search box/search bar? Or is the test outdated and no longer applicable?

Our assessment at Aperture is that yes indeed the test is outdated and no longer applicable. The MFE does not include a search bar for looking up courses. The only search box-like component is the masquerade bar, as you mentioned in the [BTR issue](https://github.com/openedx/wg-build-test-release/issues/431).

**Comment by magajh** [comment]
@MaxFrank13 Thank you for the response! Knowing this, I think we can go ahead and close this issue
